"""empty message

Revision ID: 68a266b9f879
Revises: 9bdf5995a23c
Create Date: 2026-04-19 11:19:22.788641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a266b9f879'
down_revision = '9bdf5995a23c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('apellidos',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('dni',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('embarazo',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('hepatitis',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('tuberculosis',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('vih',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('radiacion_cabeza',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('cancer',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('alergia_penicilina',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('alergia_terramicina',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('alergia_anestesia',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('alergia_latex',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('alergia_aines',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('alergia_aines',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('alergia_latex',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('alergia_anestesia',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('alergia_terramicina',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('alergia_penicilina',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('cancer',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('radiacion_cabeza',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('vih',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('tuberculosis',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('hepatitis',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('embarazo',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('dni',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('apellidos',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
