"""campos_doctor

Revision ID: 76c983c52bd6
Revises: 9ae68ea5dedd
Create Date: 2026-04-19 15:29:38.671685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c983c52bd6'
down_revision = '9ae68ea5dedd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especialidad', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('num_colegiado', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('num_colegiado')
        batch_op.drop_column('especialidad')

    # ### end Alembic commands ###
