"""empty message

Revision ID: 9bdf5995a23c
Revises: e2f5487a67a7
Create Date: 2026-04-19 10:21:55.239852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bdf5995a23c'
down_revision = 'e2f5487a67a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('end', sa.String(length=10), nullable=False))
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_column('end')
        batch_op.drop_column('start')

    # ### end Alembic commands ###
