"""empty message

Revision ID: e2f5487a67a7
Revises: 
Create Date: 2026-04-18 12:43:08.731610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f5487a67a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('patient',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('nacimiento', sa.String(length=20), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('glucosa', sa.Integer(), nullable=True),
    sa.Column('tension', sa.String(length=20), nullable=True),
    sa.Column('spo2', sa.Integer(), nullable=True),
    sa.Column('grupo_sanguineo', sa.String(length=10), nullable=True),
    sa.Column('embarazo', sa.String(length=5), nullable=False),
    sa.Column('hepatitis', sa.String(length=5), nullable=False),
    sa.Column('tuberculosis', sa.String(length=5), nullable=False),
    sa.Column('vih', sa.String(length=5), nullable=False),
    sa.Column('radiacion_cabeza', sa.String(length=5), nullable=False),
    sa.Column('cancer', sa.String(length=5), nullable=False),
    sa.Column('alergia_penicilina', sa.String(length=5), nullable=False),
    sa.Column('alergia_terramicina', sa.String(length=5), nullable=False),
    sa.Column('alergia_anestesia', sa.String(length=5), nullable=False),
    sa.Column('alergia_latex', sa.String(length=5), nullable=False),
    sa.Column('alergia_aines', sa.String(length=5), nullable=False),
    sa.Column('alergia_otros', sa.Text(), nullable=True),
    sa.Column('anotaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('appointment',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    op.drop_table('patient')
    op.drop_table('user')
    # ### end Alembic commands ###
